export let fooditemsMock = [
  {
    'name': 'Spaghetti Bolognaise',
    'description': 'w/ parmeggiano and basilikum',
    'sellerComments': 'Cooked after my grandmother\'s famous recipe',
    'pricePerPortion': 3,
    'bulkPricing': true,
    'image': 'http://drop.ndtv.com/albums/COOKS/corngallery/creolespicedcornthumb_640x480.jpg',
    'type': 'vegetarian',
    'rating': 5,
    'addressStreet': 'Marbachstraße 3',
    'addressPostalCode': '81639',
    'addressCity': 'München',
    
  },
  {
    'name': 'Cheesy Lasagna',
    'description': 'with chicken and black olives',
    'sellerComments': 'Cooked after my grandmother\'s famous recipe',
    'pricePerPortion': 4,
    'bulkPricing': false,
    'image': 'http://assets.kraftfoods.com/recipe_images/opendeploy/Table-for-Two_Lasagna_640x428.jpg',
    'type': 'non-vegetarian',
    'rating': 3,
    'addressStreet': 'Hilblesstraße 36',
    'addressPostalCode': '80686',
    'addressCity': 'München'
  },
  {
    'name': 'Gnocchi Napoli',
    'description': 'with homeoade napoli sauce',
    'sellerComments': 'Cooked after my grandmother\'s famous recipe',
    'pricePerPortion': 5.50,
    'bulkPricing': true,
    'image': 'http://www.italianicious.com.au/uploads/italianicious/articles/Ital-0312-gnocch-sorrentino-630.jpg',
    'type': 'vegetarian',
    'rating': 4,
    'addressStreet': 'Sendlingerstraße 2',
    'addressPostalCode': '80567',
    'addressCity': 'München'
  },
  {
    'name': 'Schnitzel',
    'description': 'with Lemon',
    'sellerComments': 'Cooked after my grandmother\'s famous recipe',
    'pricePerPortion': 7.50,
    'bulkPricing': false,
    'image': 'http://www.dessertfortwo.com/wp-content/uploads/2014/12/Schnitzel-2.jpg',
    'type': 'non-vegetarian',
    'rating': 5,
    'addressStreet': 'NeufahrnerStraße 19',
    'addressPostalCode': '85748',
    'addressCity': 'München'
  },
];
